# Generated by Django 5.2.1 on 2025-05-10 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='similarity',
            name='similar_movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim', to='recomender.movie'),
        ),
    ]
