# Generated by Django 5.1.6 on 2025-05-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomender', '0003_movie_adult_movie_backdrop_path_movie_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(unique=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('adult', models.BooleanField(default=False)),
                ('video', models.BooleanField(default=False)),
                ('backdrop_path', models.CharField(blank=True, max_length=500, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('budget', models.BigIntegerField(default=0)),
                ('revenue', models.BigIntegerField(default=0)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('popularity', models.FloatField(default=0)),
                ('vote_average', models.FloatField(default=0)),
                ('vote_count', models.IntegerField(default=0)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('original_language', models.CharField(blank=True, max_length=10, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('spoken_languages', models.TextField(blank=True, null=True)),
                ('production_companies', models.TextField(blank=True, null=True)),
                ('production_countries', models.TextField(blank=True, null=True)),
                ('origin_countries', models.CharField(blank=True, max_length=255, null=True)),
                ('collection_id', models.IntegerField(blank=True, null=True)),
                ('collection_name', models.CharField(blank=True, max_length=255, null=True)),
                ('collection_poster_path', models.CharField(blank=True, max_length=500, null=True)),
                ('collection_backdrop_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='adult',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='backdrop_path',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='collection_backdrop_path',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='collection_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='collection_name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='collection_poster_path',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdb_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='origin_countries',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='original_language',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='original_title',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_path',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production_companies',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production_countries',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='revenue',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='runtime',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='spoken_languages',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='status',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='vote_average',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='vote_count',
        ),
    ]
