# Generated by Django 5.1.6 on 2025-05-17 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomender', '0004_movie2_remove_movie_adult_remove_movie_backdrop_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similarity',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to='recomender.movie2'),
        ),
    ]
