# Generated by Django 5.1.6 on 2025-05-17 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomender', '0009_alter_similarity_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similarity',
            name='score',
        ),
        migrations.AlterField(
            model_name='similarity',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_movie', to='recomender.movie2'),
        ),
        migrations.AlterField(
            model_name='similarity',
            name='similar_movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_movies', to='recomender.movie2'),
        ),
    ]
