# Generated by Django 5.1.6 on 2025-05-18 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomender', '0011_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
