# Generated by Django 5.1.6 on 2025-05-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomender', '0013_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='star',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
