# Generated by Django 5.2.1 on 2025-05-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomender', '0017_alter_review_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
